#衛星打ち上げ時刻
MIN_WEEK_RANGE   = 0
MAX_WEEK_RANGE   = 50
MIN_HOUR_RANGE   = 0
MAX_HOUR_RANGE   = 24
MIN_MINUTE_RANGE = 0
MAX_MINUTE_RANGE = 60
MIN_SECOND_RANGE = 0
MAX_SECOND_RANGE = 60

#時刻データの既定値
ERROR_VALUE = 60480000

#タイムスタンプ
INITIAL_TIMESTAMP = 0

#撮影開始から終了までの時間
SHOOTING_DURATION_SECOND = 1200
