#現在の状況
SHOOTING_COMPLETION   = 0
OTHERS_COMPLETION     = 1
SHOOTING_INTERRUPTION = 2
ANALYSIS_INTERRUPTION = 3
SPLIT_INTERRUPTION    = 4
DOWNLINK_INTERRUPTION = 5

#downlink
INITIAL_DOWNLINK      = 0
AURORA_DATA           = 1
AURORA_IMG            = 2
DESIGNED_AURORA_IMG   = 3

#downlink_status
INIT_FILE_NUMBER      = 0
INIT_DESIGNED_NUMS     = []

#uplink data_size
AURORA_DATA_SIZE         = 0
AURORA_IMG_SIZE          = 1

#Elements to generate aurora_img_numbers
ELEMTNTS_IMG_FILE_NUMBER       = 3

#aurora_dataの結合数
MERGED_AURORA_DATA_NUMBER = 10